
service: aws-qiita-backup
provider:
  name: aws
  runtime: python3.6
  region: us-east-1
  stage: ${opt:stage, self:custom.defaultStage}
  environment:
    QIITA_BASE_URL: https://qiita.com/api/v2/users/{user_id}/items?page={page}&per_page=100
custom:
  defaultStage: dev
  otherfile:
    environment:
      dev: ${file(./conf/dev.yml)}
      prd: ${file(./conf/prd.yml)}

functions:
  run:
    handler: handler.run
    environment:
      S3_BUCKET: ${self:custom.otherfile.environment.${self:provider.stage}.S3_BUCKET}
      BACKUP_FILE_NAME: ${self:custom.otherfile.environment.${self:provider.stage}.BACKUP_FILE_NAME}
      SETTING_FILE_NAME: ${self:custom.otherfile.environment.${self:provider.stage}.SETTING_FILE_NAME}      
